name: MSBuild

on: 
  push:

jobs:
  build:
    runs-on: windows-2019
    steps:

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - run: dotnet build
      - run: dotnet test --logger:"nunit;LogFilePath=telt.xml"


      - name: Upload Unit Test Results
        if: ${{ always() }}

        uses: actions/upload-artifact@v2

        with:
          name: Unit Test Results
          path: ./test/telt.xml

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          nunit_files: artifacts/**/*.xml